server:
  port: 9001
spring:
  application:
    name: order-manager-cloud
  cloud:
    loadbalancer:
      ribbon:
        enabled: true
eureka:
  instance:
    hostname: ${spring.application.name}
  client:
    register-with-eureka: true #表示向注册中心注册自己
    fetch-registry: true #是否从eureka服务抓取已有的注册信息，默认为true，集群必须为true，才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://localhost:9000/eureka/